# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.box = "generic/debian10"
  else
    config.vm.box = "debian/contrib-buster64"
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8025, host: 8025
  config.vm.network "forwarded_port", guest: 3306, host: 13306

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

#  config.vm.provider "virtualbox" do |vb|
#    # Use VBoxManage to customize the VM. For example to change memory:
#    vb.customize ["modifyvm", :id, "--memory", "1024"]
#  end

  config.vm.provision "shell", path: "development/vagrant/scripts/install.sh"
  config.vm.provision "shell", path: "development/vagrant/scripts/setup.sh", privileged: false

end
