allow_failure: true

# Select what we should cache
cache:
  paths:
  - .composer/cache/files/

before_script:
  # Install git, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git -yqq

  # Install mysql driver
  - docker-php-ext-install pdo_mysql

  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Install all project dependencies
  - php composer.phar install --prefer-dist

  - cp development/travis/config.php tests/config.php

services:
  - mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: ilch2_test
  MYSQL_USER: travis
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_PASSWORD: ""

# We test PHP7.0
test-php7_0:mysql:
  image: php:7.0
  script:
    - cd test/
    - ../vendor/bin/phpunit

# We test PHP7.1
test-php7_1:mysql:
  image: php:7.1
  script:
    - cd test/
    - ../vendor/bin/phpunit

# We test PHP7.2
test-php7_2:mysql:
  image: php:7.2
  script:
    - cd test/
    - ../vendor/bin/phpunit

# We test PHP7.3
test-php7_3:mysql:
  image: php:7.3
  script:
    - cd test/
    - ../vendor/bin/phpunit

# We test PHP7.4
test-php7_4:mysql:
  image: php:7.4
  script:
    - cd test/
    - ../vendor/bin/phpunit

# We test PHP8.0
test-php8_0:mysql:
  image: php:8.0
  script:
    - cd test/
    - ../vendor/bin/phpunit

# We test PHP8.1
test-php8_1:mysql:
  image: php:8.1
  script:
    - cd test/
    - ../vendor/bin/phpunit