name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  run-ci:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php-versions: ['8.4']
        db:
          - ver: mysql
            release: '5.7'
          - ver: mariadb
            release: 10.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          tools: composer
      - name: Setup MariaDB
        if: ${{ matrix.db.ver == 'mariadb' }}
        uses: getong/mariadb-action@v1.1
        with:
          mariadb version: ${{ matrix.db.release }}
          mysql database: ilch2_test
          mysql user: ilch2_test_user
          mysql password: ilch2_test_password

      - name: Setup MySQL
        if: ${{ matrix.db.ver == 'mysql' }}
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.db.release }}
          mysql database: ilch2_test
          mysql user: ilch2_test_user
          mysql password: ilch2_test_password
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-php${{ matrix.php-versions }}
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Verify ${{ matrix.db.ver }} connection
        env:
          HOST: 127.0.0.1
          PORT: 3306
        run: |
          while ! mysqladmin ping -h"$HOST" -P"$PORT" --silent; do
            sleep 1
          done
          envsubst '$HOST,$PORT' < development/ci/config.php > tests/config.php
      - name: Execute tests
        run: cd tests && ../vendor/bin/phpunit
